/**
 * Engine boundary types — the TS side of the host/Rill contract.
 * All types are JSON-serializable by construction (no functions, no Dates).
 */

export type SessionPhase = 'idle' | 'warmup' | 'working' | 'resting' | 'paused' | 'done';
export type SetType = 'warmup' | 'working' | 'stretch' | 'cardio';
export type ExerciseKind = 'strength' | 'cardio' | 'stretch';

/**
 * The prescribed type of a planned set. Deliberately narrower than `SetType`,
 * which is the *logged* type: a plan says only "warmup" or "normal", and the
 * engine turns a non-warmup set into `working`/`stretch`/`cardio` from the
 * exercise's own kind at log time.
 */
export type RoutineSetType = 'warmup' | 'normal';

/**
 * One prescribed set. Every measurement is optional, and absent means absent —
 * these fields are new surface with no legacy read sites to protect, so they
 * are deliberately NOT added to SENTINEL_TO_OPTION_MAP (convention 8). Read
 * sites must use `!= null`: WatermelonDB hands back `null` for an unset
 * optional column, and `rillToJs` omits a `None` key entirely.
 */
export interface RoutineSet {
  setType: RoutineSetType;
  reps?: number | null;
  repsMax?: number | null;
  weightKg?: number | null;
  durationSeconds?: number | null;
  distanceM?: number | null;
}

export interface RoutineEntry {
  idx: number; // Index for Rill lookup (host pre-indexes entries)
  exerciseId: string;
  kind: ExerciseKind;
  restSeconds: number;
  supersetGroup: string; // "" means no superset
  /**
   * The ordered prescription the engine advances through — REQUIRED, and the
   * only representation of the plan as of #276 Phase 6.
   *
   * It was optional through Phases 2–5 while four aggregate count fields
   * (`warmupSets`, `targetSets`, `targetReps`, `targetDurationSeconds`) sat
   * beside it and a derivation seam bridged the two. Both directions of that
   * seam are gone: nothing expands counts into a list on the way in, and
   * nothing re-derives counts from a list on the way out.
   *
   * `[]` is a legal value and means the entry prescribes nothing. It is NOT the
   * same as a missing list, which is why this is required rather than optional
   * with an empty default — an entry the caller forgot to give a plan is a bug
   * the type system can catch, and an entry that genuinely plans nothing is a
   * shape convention 10 handles.
   */
  sets: RoutineSet[];
}

export interface LoggedSet {
  exerciseId: string;
  setType: SetType;
  reps: number | null | undefined;
  weightKg: number | null | undefined;
  durationSeconds: number | null | undefined;
  rpe: number | null | undefined;
}

/**
 * SessionState: JSON-serializable session data.
 * Note: entries (routine structure) is stored in state so it's available for all transitions.
 * This keeps the state self-contained and serializable (can be persisted and rehydrated).
 * lastLoggedSet: host-maintained field; populated by rill LogSet handler, read by host on persist_set effect.
 * prePausePhase: sentinel phase before PauseSession (empty string "" = no pause recorded), used by Resume.
 */
export interface SessionState {
  sessionId: string;
  routineId: string;
  phase: SessionPhase;
  exerciseIndex: number;
  setIndex: number;
  supersetPosition?: number;
  restDeadlineMs?: number;
  restRemainingMs?: number; // Rest time frozen while paused mid-rest (0 = nothing frozen)
  loggedSets: LoggedSet[];
  lastLoggedSet?: LoggedSet; // Host-maintained; set by rill LogSet handler
  startedAtMs: number;
  prePausePhase?: string; // Sentinel for Resume: "" = no pause recorded, else the phase before pause
  entries: RoutineEntry[]; // Routine structure — needed for advancement logic
}

/**
 * Event (discriminated union) — all events generated by the host.
 * The Rill engine receives (state, event) and emits a new state + effects.
 */
export type Event =
  | { tag: 'StartSession'; sessionId: string; nowMs: number; routine: unknown }
  | { tag: 'LogSet'; reps?: number; weightKg?: number; durationSeconds?: number; rpe?: number; nowMs: number }
  | { tag: 'SetDone'; nowMs: number }
  | { tag: 'RestElapsed'; nowMs: number }
  | { tag: 'SkipRest' }
  // Swap which exercise the entry at `idx` names, leaving its targets,
  // warmups, rest and superset group alone. `idx` is the 0-based entry
  // position and must equal the current exerciseIndex — the rule rejects a
  // pick made about an entry the workout has already moved past.
  | { tag: 'ReplaceExercise'; idx: number; exerciseId: string }
  | { tag: 'PauseSession'; nowMs: number }
  | { tag: 'Resume'; nowMs: number }
  | { tag: 'AppForegrounded'; nowMs: number }
  | { tag: 'FinishSession'; nowMs: number }
  | { tag: 'AbandonSession' };

/**
 * Effect (discriminated union) — all side effects emitted by the engine.
 */
export type Effect =
  | { tag: 'CreateSession'; sessionId: string; routineId: string; startedAtMs: number }
  | { tag: 'ScheduleRest'; deadlineMs: number }
  | { tag: 'CancelRest' }
  | { tag: 'Notify'; message: string }
  | { tag: 'PersistSet'; set: LoggedSet }
  | { tag: 'CompleteSession'; summary: unknown }
  | { tag: 'DiscardSession'; sessionId: string };
