/**
 * Engine boundary types — the TS side of the host/Rill contract.
 * All types are JSON-serializable by construction (no functions, no Dates).
 */

export type SessionPhase = 'idle' | 'warmup' | 'working' | 'resting' | 'stretching' | 'paused' | 'done';
export type SetType = 'warmup' | 'working' | 'stretch' | 'cardio';
export type ExerciseKind = 'strength' | 'cardio' | 'stretch';

export interface RoutineEntry {
  idx: number; // Index for Rill lookup (host pre-indexes entries)
  exerciseId: string;
  kind: ExerciseKind;
  warmupSets: number;
  targetSets: number;
  targetReps: number;
  targetDurationSeconds: number;
  restSeconds: number;
  supersetGroup: string; // "" means no superset
}

export interface LoggedSet {
  exerciseId: string;
  setType: SetType;
  reps: number | null | undefined;
  weightKg: number | null | undefined;
  durationSeconds: number | null | undefined;
  rpe: number | null | undefined;
}

/**
 * SessionState: JSON-serializable session data.
 * Note: entries (routine structure) is stored in state so it's available for all transitions.
 * This keeps the state self-contained and serializable (can be persisted and rehydrated).
 * lastLoggedSet: host-maintained field; populated by rill LogSet handler, read by host on persist_set effect.
 * prePausePhase: sentinel phase before PauseSession (empty string "" = no pause recorded), used by Resume.
 */
export interface SessionState {
  sessionId: string;
  routineId: string;
  phase: SessionPhase;
  exerciseIndex: number;
  setIndex: number;
  supersetPosition?: number;
  restDeadlineMs?: number;
  restRemainingMs?: number; // Rest time frozen while paused mid-rest (0 = nothing frozen)
  loggedSets: LoggedSet[];
  lastLoggedSet?: LoggedSet; // Host-maintained; set by rill LogSet handler
  startedAtMs: number;
  prePausePhase?: string; // Sentinel for Resume: "" = no pause recorded, else the phase before pause
  entries: RoutineEntry[]; // Routine structure — needed for advancement logic
}

/**
 * Event (discriminated union) — all events generated by the host.
 * The Rill engine receives (state, event) and emits a new state + effects.
 */
export type Event =
  | { tag: 'StartSession'; sessionId: string; nowMs: number; routine: unknown }
  | { tag: 'LogSet'; reps?: number; weightKg?: number; durationSeconds?: number; rpe?: number }
  | { tag: 'SetDone'; nowMs: number }
  | { tag: 'RestElapsed'; nowMs: number }
  | { tag: 'SkipRest' }
  | { tag: 'SkipExercise' }
  | { tag: 'PauseSession'; nowMs: number }
  | { tag: 'StartStretching' }
  | { tag: 'Resume'; nowMs: number }
  | { tag: 'FinishSession'; nowMs: number }
  | { tag: 'AbandonSession' };

/**
 * Effect (discriminated union) — all side effects emitted by the engine.
 */
export type Effect =
  | { tag: 'CreateSession'; sessionId: string; routineId: string; startedAtMs: number }
  | { tag: 'ScheduleRest'; deadlineMs: number }
  | { tag: 'CancelRest' }
  | { tag: 'Notify'; message: string }
  | { tag: 'PersistSet'; set: LoggedSet }
  | { tag: 'CompleteSession'; summary: unknown }
  | { tag: 'DiscardSession'; sessionId: string };
