/**
 * `importRoutine` — the pure half of the markdown import path (#267 Phase 2).
 *
 * Covers AC2.1 (the RAMP round-trip), AC2.5 (a malformed document is refused by
 * name, before anything reaches the DB half) and AC2.6 (non-contiguous superset
 * labels, and a routine that plans nothing at all).
 *
 * The RAMP fixture is a LITERAL document rather than one generated by calling
 * the serializer inside the assertion: a generated fixture drifts with the code
 * under test's sibling and can no longer pin bytes. `serializeRoutine` still
 * gets to prove the literal is the real thing — the first test re-emits RAMP
 * from its row shape and compares, so the fixture cannot go stale silently.
 */

import { serializeRoutine } from '../serialize';
import { importRoutine } from '../importRoutine';

/**
 * RAMP — Bench Press (Dumbbell) from the real Hevy Push payload: three warmups
 * at three DIFFERENT loads, then four working sets of 8–10 at one load. The
 * aggregate model this replaced could not hold it, which is what makes it the
 * discriminating fixture for the whole feature: a per-exercise importer returns
 * ONE weight where this asserts seven.
 */
const RAMP_ROUTINE_ROW = {
  id: 'routine-1755300000000',
  name: 'Push',
  createdAt: new Date('2026-08-16T00:00:00Z'),
  updatedAt: new Date('2026-08-16T00:00:00Z'),
};

const RAMP_ENTRY_ROWS = [
  {
    id: 're-1',
    exerciseId: 'bench-press-dumbbell',
    order: 0,
    restSeconds: 120,
    notes: 'Up to 50 lb.',
    sets: [
      { setType: 'warmup' as const, targetReps: 5, targetWeightKg: 9.07 },
      { setType: 'warmup' as const, targetReps: 5, targetWeightKg: 11.34 },
      { setType: 'warmup' as const, targetReps: 3, targetWeightKg: 18.14 },
      { setType: 'normal' as const, targetReps: 8, targetRepsMax: 10, targetWeightKg: 22.68 },
      { setType: 'normal' as const, targetReps: 8, targetRepsMax: 10, targetWeightKg: 22.68 },
      { setType: 'normal' as const, targetReps: 8, targetRepsMax: 10, targetWeightKg: 22.68 },
      { setType: 'normal' as const, targetReps: 8, targetRepsMax: 10, targetWeightKg: 22.68 },
    ],
  },
  {
    id: 're-2',
    exerciseId: 'cable-fly',
    order: 1,
    supersetGroup: '5',
    restSeconds: 60,
    sets: [{ setType: 'normal' as const, targetReps: 12, restSeconds: 0 }],
  },
  {
    id: 're-3',
    exerciseId: 'lateral-raise',
    order: 2,
    supersetGroup: '5',
    restSeconds: 60,
    sets: [{ setType: 'normal' as const, targetReps: 15 }],
  },
  {
    id: 're-4',
    exerciseId: 'treadmill',
    order: 3,
    sets: [{ setType: 'normal' as const, targetDurationSeconds: 300, targetDistanceM: 2000 }],
  },
  { id: 're-5', exerciseId: 'stretching', order: 4, sets: [] },
];

const RAMP_EXERCISE_ROWS = [
  { id: 'bench-press-dumbbell', title: 'Bench Press (Dumbbell)', kind: 'strength' as const },
  { id: 'cable-fly', title: 'Cable Fly', kind: 'strength' as const },
  { id: 'lateral-raise', title: 'Lateral Raise', kind: 'strength' as const },
  { id: 'treadmill', title: 'Treadmill', kind: 'cardio' as const },
  { id: 'stretching', title: 'Stretching', kind: 'stretch' as const },
];

const RAMP_MARKDOWN = `---
type: workout-routine
id: routine-1755300000000
name: Push
updated: 2026-08-16
tags: []
created: 2026-08-16
---

\`\`\`workout
- bench-press-dumbbell: 1x5 rest=2:00 set_type=warmup target_weight=9.07 @"Up to 50 lb."
- bench-press-dumbbell: 1x5 rest=2:00 set_type=warmup target_weight=11.34 @"Up to 50 lb."
- bench-press-dumbbell: 1x3 rest=2:00 set_type=warmup target_weight=18.14 @"Up to 50 lb."
- bench-press-dumbbell: 1x8 rest=2:00 reps_max=10 target_weight=22.68 @"Up to 50 lb."
- bench-press-dumbbell: 1x8 rest=2:00 reps_max=10 target_weight=22.68 @"Up to 50 lb."
- bench-press-dumbbell: 1x8 rest=2:00 reps_max=10 target_weight=22.68 @"Up to 50 lb."
- bench-press-dumbbell: 1x8 rest=2:00 reps_max=10 target_weight=22.68 @"Up to 50 lb."
- cable-fly: 1x12 rest=1:00 superset=5 set_rest=0
- lateral-raise: 1x15 rest=1:00 superset=5
- treadmill: kind=cardio duration=5:00 target_distance=2000
- stretching: sets=0 kind=stretch
\`\`\`
`;

/** A minimal well-formed document, for the error fixtures to mutate. */
function doc(lines: string[], frontmatter = 'name: Test Routine'): string {
  return `---
type: workout-routine
id: routine-1
${frontmatter}
updated: 2026-08-16
tags: []
created: 2026-08-16
---

\`\`\`workout
${lines.join('\n')}
\`\`\`
`;
}

function expectOk(markdown: string) {
  const result = importRoutine(markdown);
  if (!result.ok) {
    throw new Error(`expected ok, got ${result.error.code}: ${result.error.message}`);
  }
  return result.routine;
}

function expectErrorCode(markdown: string): string {
  const result = importRoutine(markdown);
  if (result.ok) {
    throw new Error('expected a named error, got a routine');
  }
  return result.error.code;
}

describe('importRoutine — the fixture is the real exported document', () => {
  it('is byte-identical to what serializeRoutine emits for RAMP', () => {
    // Pins the literal above against the serializer. Without this, a change to
    // `serialize.ts` leaves the import tests passing against a document the app
    // no longer produces — the exact drift the #295 lattice exists to catch on
    // the other leg.
    expect(serializeRoutine(RAMP_ROUTINE_ROW, RAMP_ENTRY_ROWS, RAMP_EXERCISE_ROWS)).toBe(
      RAMP_MARKDOWN
    );
  });
});

describe('importRoutine — AC2.1: the warmup ramp survives the round trip', () => {
  it('returns seven sets for the ramp entry, with three distinct ascending warmup loads', () => {
    const routine = expectOk(RAMP_MARKDOWN);
    const ramp = routine.entries[0];

    expect(ramp.exerciseId).toBe('bench-press-dumbbell');
    expect(ramp.sets).toHaveLength(7);
    expect(ramp.sets.map((s) => s.setType)).toEqual([
      'warmup',
      'warmup',
      'warmup',
      'normal',
      'normal',
      'normal',
      'normal',
    ]);
    // The headline assertion: three DISTINCT ascending warmup weights, then the
    // working load repeated. A per-exercise importer returns one number here.
    expect(ramp.sets.map((s) => s.targetWeightKg)).toEqual([
      9.07, 11.34, 18.14, 22.68, 22.68, 22.68, 22.68,
    ]);
    expect(ramp.sets.map((s) => s.targetReps)).toEqual([5, 5, 3, 8, 8, 8, 8]);
    expect(ramp.sets.map((s) => s.targetRepsMax)).toEqual([
      undefined,
      undefined,
      undefined,
      10,
      10,
      10,
      10,
    ]);
  });

  it('carries every entry-level field back onto the entry', () => {
    const routine = expectOk(RAMP_MARKDOWN);

    expect(routine.entries.map((e) => e.exerciseId)).toEqual([
      'bench-press-dumbbell',
      'cable-fly',
      'lateral-raise',
      'treadmill',
      'stretching',
    ]);
    expect(routine.entries.map((e) => e.order)).toEqual([0, 1, 2, 3, 4]);
    expect(routine.entries[0].restSeconds).toBe(120);
    expect(routine.entries[0].notes).toBe('Up to 50 lb.');
    expect(routine.entries.map((e) => e.supersetGroup)).toEqual([
      undefined,
      '5',
      '5',
      undefined,
      undefined,
    ]);
  });

  it('keeps a per-set rest override of 0 distinct from "inherit"', () => {
    // `set_rest=0` is a drop set's zero rest and must not collapse into absent
    // (AGENTS.md: guard on `!= null`, never truthiness).
    const routine = expectOk(RAMP_MARKDOWN);
    expect(routine.entries[1].sets[0].restSeconds).toBe(0);
    expect(routine.entries[2].sets[0].restSeconds).toBeUndefined();
  });

  it('carries duration and distance back onto a cardio set', () => {
    const routine = expectOk(RAMP_MARKDOWN);
    expect(routine.entries[3].sets).toEqual([
      { setType: 'normal', targetDurationSeconds: 300, targetDistanceM: 2000 },
    ]);
  });

  it('reads an entry that prescribes nothing as an empty set list, not a dropped entry', () => {
    const routine = expectOk(RAMP_MARKDOWN);
    expect(routine.entries[4].exerciseId).toBe('stretching');
    expect(routine.entries[4].sets).toEqual([]);
  });
});

describe('importRoutine — the exercises the DB half has to create', () => {
  it('names each distinct exercise once, with a kind and a title that slugifies back to its id', () => {
    const routine = expectOk(RAMP_MARKDOWN);
    expect(routine.exercises).toEqual([
      { id: 'bench-press-dumbbell', title: 'Bench Press Dumbbell', kind: 'strength' },
      { id: 'cable-fly', title: 'Cable Fly', kind: 'strength' },
      { id: 'lateral-raise', title: 'Lateral Raise', kind: 'strength' },
      { id: 'treadmill', title: 'Treadmill', kind: 'cardio' },
      { id: 'stretching', title: 'Stretching', kind: 'stretch' },
    ]);
  });

  it('lists a repeated exercise once, not once per entry', () => {
    const routine = expectOk(doc(['- back-squat: 1x5', '- back-squat: 1x5']));
    // Two LINES of one exercise fold into one entry; two ENTRIES need two
    // separated by another exercise.
    const twice = expectOk(doc(['- back-squat: 1x5', '- deadlift: 1x3', '- back-squat: 1x5']));
    expect(routine.exercises.map((e) => e.id)).toEqual(['back-squat']);
    expect(twice.entries).toHaveLength(3);
    expect(twice.exercises.map((e) => e.id)).toEqual(['back-squat', 'deadlift']);
  });
});

describe('importRoutine — the routine name', () => {
  it('reads the name out of the frontmatter', () => {
    expect(expectOk(RAMP_MARKDOWN).name).toBe('Push');
  });

  it('keeps a name containing a colon whole', () => {
    const routine = expectOk(doc(['- back-squat: 1x5'], 'name: Push: Day One'));
    expect(routine.name).toBe('Push: Day One');
  });

  it('falls back to the frontmatter id when a document carries no name', () => {
    // Documents exported before the `name:` key existed still import; they just
    // arrive named after their id rather than silently blank.
    const noName = `---
type: workout-routine
id: routine-1755300000000
updated: 2026-08-16
tags: []
created: 2026-08-16
---

\`\`\`workout
- back-squat: 1x5
\`\`\`
`;
    expect(expectOk(noName).name).toBe('routine-1755300000000');
  });
});

describe('importRoutine — AC2.5: a malformed document is refused, by name', () => {
  it('refuses an unknown flag key', () => {
    expect(expectErrorCode(doc(['- back-squat: 1x5 bogus=3']))).toBe('unparseable');
  });

  it('refuses an unparseable sets slot', () => {
    expect(expectErrorCode(doc(['- back-squat: 3x5']))).toBe('unparseable');
    expect(expectErrorCode(doc(['- back-squat: 1xmany']))).toBe('unparseable');
  });

  it('refuses a document with no frontmatter', () => {
    expect(expectErrorCode('```workout\n- back-squat: 1x5\n```\n')).toBe('unparseable');
  });

  it('refuses a document with no workout block', () => {
    expect(
      expectErrorCode('---\ntype: workout-routine\nid: routine-1\n---\n\nnothing here\n')
    ).toBe('unparseable');
  });

  it('names the failure in a message a screen can render', () => {
    const result = importRoutine(doc(['- back-squat: 1x5 bogus=3']));
    expect(result.ok).toBe(false);
    if (result.ok) return;
    expect(result.error.message.length).toBeGreaterThan(0);
  });

  it('refuses a document whose workout block has no exercises', () => {
    expect(expectErrorCode(doc([]))).toBe('empty-routine');
  });
});

describe('importRoutine — AC2.6: shapes the engine cannot run', () => {
  it('accepts a contiguous superset run', () => {
    const routine = expectOk(
      doc(['- cable-fly: 1x12 superset=5', '- lateral-raise: 1x15 superset=5'])
    );
    expect(routine.entries.map((e) => e.supersetGroup)).toEqual(['5', '5']);
  });

  it('accepts two DIFFERENT runs that happen to be adjacent', () => {
    // Labels are contiguous but not routine-unique; adjacency of two distinct
    // labels is ordinary, not a violation.
    const routine = expectOk(
      doc([
        '- cable-fly: 1x12 superset=5',
        '- lateral-raise: 1x15 superset=5',
        '- curl: 1x10 superset=6',
        '- pushdown: 1x10 superset=6',
      ])
    );
    expect(routine.entries.map((e) => e.supersetGroup)).toEqual(['5', '5', '6', '6']);
  });

  it('refuses a label that reappears after a gap', () => {
    // `h.group_end_idx` scans forward for a CONTIGUOUS run; a split label would
    // silently import as two groups that the engine runs as one shape and the
    // routine screen renders as another.
    expect(
      expectErrorCode(
        doc([
          '- cable-fly: 1x12 superset=5',
          '- back-squat: 1x5',
          '- lateral-raise: 1x15 superset=5',
        ])
      )
    ).toBe('non-contiguous-superset');
  });

  it('refuses a routine where every entry plans nothing', () => {
    // The same refusal `startSessionFromRoutine` already makes, one layer
    // earlier: importing an unstartable routine is not a useful outcome.
    expect(expectErrorCode(doc(['- back-squat: sets=0', '- deadlift: sets=0']))).toBe(
      'no-planned-sets'
    );
  });

  it('accepts a routine where only SOME entries plan nothing', () => {
    // Discriminates the refusal above from "reject any zero-set entry": an
    // entry the routine names but prescribes nothing for is legal (convention 10).
    const routine = expectOk(doc(['- back-squat: sets=0', '- deadlift: 1x3']));
    expect(routine.entries.map((e) => e.sets.length)).toEqual([0, 1]);
  });
});
